# Generated by Django 3.2.5 on 2021-09-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
    ]
