# Generated by Django 3.2.5 on 2021-08-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hits',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='Рейтинг'),
        ),
    ]
