# Generated by Django 3.2.5 on 2021-09-02 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_hits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-hits',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
