# Generated by Django 3.2.5 on 2021-09-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upload_xml',
            field=models.BooleanField(default=False, verbose_name='Выгрузить на Я.Маркет'),
        ),
    ]
