# Generated by Django 3.2.5 on 2021-09-06 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0004_product_upload_xml'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Телефон')),
                ('delivery', models.CharField(choices=[('S', 'Самовывоз'), ('R', 'Почта россии'), ('C', 'Сдэк'), ('B', 'Boxberry')], max_length=1, null=True, verbose_name='Требуется доставка?')),
                ('address_PVZ', models.CharField(blank=True, max_length=250, verbose_name='Пункт самовывоза')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Адрес')),
                ('postal_code', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='Почтовый индекс')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион/Область')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итоговая стоимость')),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product')),
            ],
        ),
    ]
