# Generated by Django 3.2.5 on 2021-09-06 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_status'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.status', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='order',
            name='url_pay',
            field=models.URLField(blank=True, default=None, max_length=255, null=True, verbose_name='Ссылка для оплаты'),
        ),
    ]
