# Generated by Django 3.2.5 on 2021-09-06 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_status_options'),
        ('orders', '0002_auto_20210906_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('S', 'Самовывоз'), ('R', 'Почта россии'), ('C', 'Сдэк'), ('B', 'Boxberry')], max_length=1, verbose_name='Требуется доставка?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='url_pay',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Ссылка для оплаты'),
        ),
    ]
